# Generated by Django 2.0.4 on 2018-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_auto_20180422_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Concluído'), ('P', 'Pendente')], default='P', help_text='O estado do processo: pendente ou concluído', max_length=1),
        ),
    ]
