# Generated by Django 2.0.4 on 2018-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='archive',
            field=models.FileField(help_text='Um arquivo .pdf com todos os documentos do processo', upload_to=''),
        ),
    ]
